--- 
title: "Proyecto Análisis"
output:
  html_document:
    toc: true
    toc_depth: 2
author: "Maddi Casaiz y Ana Díaz"
date: "`r Sys.Date()`"
--- 


```{r include=FALSE}
library(sf)
library(ggplot2)
library(leaflet)
library(osmdata)
library(dplyr)
library(readr)
library(lubridate)

```

Importar y preparar la base de datos para el estudio que queremos realizar

```{r}
datos <- read_csv("aemet_datos_diarios.csv")
datos$fecha <- as.Date(datos$fecha, format="%Y-%m-%d")
datos$año <- year(datos$fecha)
datos$mes <- month(datos$fecha)
estaciones <- c()

for (mes in datos$mes) {
  if (mes >= 3 && mes <= 5) {
    estaciones <- c(estaciones, 'primavera')
  } else if (mes >= 6 && mes <= 8) {
    estaciones <- c(estaciones, 'verano')
  } else if (mes >= 9 && mes <= 11) {
    estaciones <- c(estaciones, 'otoño')
  } else {
    estaciones <- c(estaciones, 'invierno')
  }
}
datos$estacion <- estaciones
datos$tmax <- as.character(datos$tmax)
datos$tmin <- as.character(datos$tmin)
datos$tmed <- as.character(datos$tmed)
datos$tmax <- parse_number(datos$tmax) / 10  
datos$tmin <- parse_number(datos$tmin) / 10
datos$tmed <- parse_number(datos$tmed) / 10

datos <- datos[!is.na(datos$tmin) & !is.na(datos$tmed) & !is.na(datos$tmax), ]
```
#Evolución de las temperaturas a lo largo de los años 

Regresión lineal de las temperaturas desde 2000

```{r}

modelo  <- lm(tmed ~ año, data = datos)
coef = coefficients(modelo)
recta1 = coef[1] + seq(2000,2025,1)* coef[2]
x <- seq(2000,2025,1)
plot(tmed ~ año, data = datos,
        ylab="Temperatura máxima (°C)",
        xlab="Año",
        main="Temperaturas diarias")

lines(x, recta1)
```

Añadamos a esta gráfica las temperaturas mínimas y la temperatura media

```{r}
modelo2  <- lm(tmin ~ año, data = datos)
coef2 = coefficients(modelo2)
recta2 = coef2[1] + seq(2000,2025,1)* coef2[2]

lines(x, recta2)

modelo3  <- lm(tmin ~ año, data = datos)
coef3 = coefficients(modelo3)
recta3 = coef3[1] + seq(2000,2025,1)* coef3[2]

lines(x, recta3)
```


#Relacion entre las medias de temperatura alta y baja

```{r}
boxplot(tmax ~ tmin, data = datos)
t.test(tmax ~ tmin, data = datos, paired = True)


```


#¿El calentamiento afecta a todas las estaciones por igual?
